#!/bin/bash

echo "Ecrit un message et laisse la magie operer:"
read message
echo $message | sed -e "y/abcdefghijklmnopqrstuvwxyz,'/ɐqɔpǝɟƃɥıɾʞlɯuodbɹsʇnΛmxλz',/" | rev
echo "veux tu voir un truc de fou ?"
select yno in Yes No
	do
			case $yno in
			"Yes") echo "	'oooo'\nreverse:'oooo'\n C'est juste DINGUE en fait";
			break;;
			"No") echo "Bah super , 0 fun, geniale";
			break;;
			esac
			done
